### ISSUE TITLE
Update contact creates a duplicate

### ISSUE THREAD

**Issue by cameronhaddad** [loopline-systems/closeio-api-wrapper#26]
When trying to update an existing contact on a lead, instead of overriding the existing contact object a new one is being created.

This is due to the clearing of the id attribute on the contact before sending the request within the ContactApi::updateContact(Contact $contact) function. (Line 93 - $contact->setId(null);)

Could you please remove this line.

**Comment by mickadoo** [comment]
I believe the ID is set as part of the URL, and was intentionally removed from the request body. You can see on [this line](https://github.com/loopline-systems/closeio-api-wrapper/blob/develop/src/LooplineSystems/CloseIoApiWrapper/Api/ContactApi.php#L96) that it's passed to the `prepareRequest` method, which substitutes the `:id` placeholder with the actual ID. Maybe something has changed on close.io, but could you first confirm that the ID is not null at this point.

**Comment by cameronhaddad** [comment]
I saw the comment, but when updating a contact it was duplicating that contact within the lead.  I commented out this line and the contact was updated and not duplicated.

[Not sure if the API has changed](https://developer.close.io/#contacts-update-an-existing-contact) , the example doesn't suggest you need to send the ID field.  But you can do a quick test and reproduce this if  need be.  Definitely duplicating the contact for me.

**Comment by mickadoo** [comment]
Maybe @philfreo would be able to tell us if something changes in the API. As @cameronhaddad said, it doesn't look like you need to include the ID in the request body to update an existing contact.

**Comment by cameronhaddad** [comment]
I'm not sure about not including it in the request body.  But in the update function of the ContactAPI class, the id attribute is set to null on the contact object before the request.  This is the line that is causing a new contact to be created.

**Comment by philfreo** [comment]
I don't think anything has changed in the API about this, at least not anytime recently. Let me know if something is unclear from the API docs. 

If you're trying to update a contact, I strongly suggest using the PUT /contact/{id}/ rather than doing a PUT to /lead/{id}/ with nested contacts.

**Comment by mickadoo** [comment]
@cameronhaddad could you try @philfreo's suggestion of doing the update on the contact. Nested updates are a pain to keep track of, both in the API wrapper and, I'm sure, for the close.io API team. It's always cleaner to do updates on a single entity using only that entity's properties.

**Comment by cameronhaddad** [comment]
I believe that is what I am already doing (see snippet below).  I am using the Contact API to update a contact directly.  But it is just duplicating that contact within the lead, because in the update function the ID is wiped, and the API must think its a new object.

    function addPhoneToLeadContact($inpCloseLeadid, inpMobile)
    {
        $closeIoConfig = new CloseIoConfig();
        $closeIoConfig->setApiKey($CLOSE_IO_API_KEY);
        
        $closeIoApiWrapper = new CloseIoApiWrapper($closeIoConfig);
        $close_leadsApi = $closeIoApiWrapper->getLeadApi();
        
        $close_lead = $close_leadsApi->getLead($inpCloseLeadid);
        
        $arrContacts = $close_lead->getContacts();
        $close_contact = $arrContacts[0];
        
        $close_phone = new Close_Phone();
        $close_phone->setPhone(inpMobile);
        $close_phone->setType(Phone::PHONE_TYPE_MOBILE);
        $close_contact->addPhone(close_contact);
        
        $close_contactApi = $closeIoApiWrapper->getContactApi();
        $close_contactApi->updateContact($close_contact);
    }

**Comment by philfreo** [comment]
Can you output the raw HTTP request or at least the actual JSON data sent?

**Comment by cameronhaddad** [comment]
I solved my issue with a bit of trial and error after looking at the HTTP response.

By re-getting the lead from the lead API after updating one of its contacts, it preventing the duplicate from being created.   As the contact attached to it was stale.

I was getting the lead, then iterating its contact array to find the contact to update.  Then updating that contact via the contactAPI and returning.   Updating some info on the lead and calling updateLead on the lead API, **which had a stale version of the contact.**    It was at this point when the old contact object was being re-added as a duplicate.

**Comment by cameronhaddad** [comment]
Thank you for your help guys.

**Comment by mickadoo** [comment]
Good to hear you found the cause. If you want to suggest any changes you can open another issue describing how you think it could be improved.
