### ISSUE TITLE
SMS Feature

### ISSUE THREAD

**Issue by phillypro** [loopline-systems/closeio-api-wrapper#33]
hey whatsup 

its been awhile....but i was curious....do you have any plans to implement the sms feature on closeio?

i really want to create a system

**Comment by mickadoo** [comment]
Hey @phillypro, I don't think we have plans to work on this unless @marczahn or @null9beta has some time. To be honest, I'm not really working so much with close.io right now, although I'm happy to keep an eye on this and review / merge PRs when they come up. 

I'm not sure how the other two maintainers feel, but it might make sense to open this up and add some other maintainers if you're using close.io regularly and notice some missing features / bugs.

**Comment by phillypro** [comment]
maybe i might be able to get a question ive been struggling with answered
then lol

i remember a while back...i had a function added called findLeads....but it
stopped working because the leads that got returned were no longer an array
but an object....or something like that

my question is.....is there a function currently in this package that
operates as simple as

  $s                 = $leadsApi->findLeads(['phone' => $phone]);


to pull matching results from close.io?

**Comment by mickadoo** [comment]
`findLeads` is [still there](https://github.com/loopline-systems/closeio-api-wrapper/blob/develop/src/LooplineSystems/CloseIoApiWrapper/Api/LeadApi.php#L66) and it accepts query parameters just like in your example.

I remember we changed the return type in one release to make it consistent across all APIs. It shouldn't have changed anything except the return type though, so if it was working for you before it should still work now.

As to whether close.io will accept querying leads by a single phone number, I can't answer that. Their [developer docs](https://developer.close.io/#leads) don't show an example using phone in the `GET lead` request. If you want to find which lead owns a specific phone number you could use their [phone API](https://developer.close.io/#phone-numbers) which looks like it would allow `GET /phone_number/?number=03298213290`. You might be able to follow the foreign keys in this response to trace it to a lead.

**Comment by wodka** [comment]
I just added a pull request for the SMS Activities: https://github.com/loopline-systems/closeio-api-wrapper/pull/34

**Comment by mickadoo** [comment]
Closing as this was implemented by @wodka in #34. Will try put a release together soon, until then if you want to test it using develop that would be a big help @phillypro
