### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by mickadoo** [loopline-systems/closeio-api-wrapper#37]
This repo was created a few years ago and some of us have moved on or are not using close.io as much. It's great to see some PRs from the community, but sometimes they're left open for a long time. It seems to be reasonably popular ([10,000 downloads](https://packagist.org/packages/loopline-systems/closeio-api-wrapper) although about 3,000 of those were probably me during early development) and instead of having individual forks by people who get fed up waiting I think it might be better to give some people merge rights on it.

It's not a huge responsibility, there aren't a whole lot of new PRs, but for someone who's using close.io through a PHP application right now it could be a good chance to step up your with this repo.

Pinging a few people who have contributed in the past:
@mavimo @danbarker @kasparsj @wodka @wridgers @filchakov @dlimars @EnoahNetzach 

Just leave a comment here if you're interested

**Comment by mavimo** [comment]
@mickadoo we continue to use it and should be happy to take ownership/help you on maintenance/evolution; you can ping me on twitter (same nick) or via mail (same nick at gmail).

**Comment by danbarker** [comment]
@mickadoo - Thanks for all your work!

We are still using this and may occasionally make changes so I'm happy to take on merge rights so I can merge them in to the main repo for others to use. I'm extremely limited for time and resources though (being a developer is not my main job)  so can't really take on the responsibility of being the lead contributor, and am unlikely to be able to merge others' PRs.

**Comment by mickadoo** [comment]
@mavimo sent me a big email outlining their ideas for this repo, so I'm happy to have them as a new collaborator.

@danbarker if you feel like your permissions are limiting your contributions to this just let me know and we can think about adding you too. 

By adding new collaborators I'm hoping nothing will change with the review process, PRs should still be reviewed (and pass the tests) before being merged, just it should be easier with more eyes and ears to avoid having some PRs stuck for a while.

**Comment by mavimo** [comment]
@mickadoo thx for work you do on this project and for open source it and thanks to give me opportunity to contribute :)
