### ISSUE TITLE
Add check on coding standard

### ISSUE THREAD

**Issue by mavimo** [loopline-systems/closeio-api-wrapper#61]
Add CI step to ensure coding standard, some CS we should evaluate:

 - [ ] https://github.com/consistence/coding-standard
 - [ ] https://github.com/slevomat/coding-standard
 - [ ] https://github.com/djoos/Symfony-coding-standard

I'll add on version 0.8 since most of them do not support php 5.6 as we do on 0.7

**Comment by ste93cry** [comment]
Since this has been done in #94 I believe you can close this issue
