### ISSUE TITLE
Finalize 0.7

### ISSUE THREAD

**Issue by mavimo** [loopline-systems/closeio-api-wrapper#79]
Hi, I'm going to finalise [0.7](https://github.com/loopline-systems/closeio-api-wrapper/milestone/1) in the next few days; I'll like any effort on review the changes in the planned release and have information from users that use this library to know if there are some change that can break the library usage.
This release should be completely full back compatible but in case of issue let me know and I'll try to fix it before the release.

cc/ @kasparsj @wridgers @wodka @DaneEveritt @mickadoo @null9beta @nickpersico @philfreo @dlimars @filchakov @CKaller @MarcoKollosche @raizalc @SarahPAV @it-slave @closeio @yearbook @muffeen @igor-kamil @filchakov

**Comment by mickadoo** [comment]
Thanks for all the work @mavimo, some really nice clean up and attention for a repo that has been a bit forgotten about over the last while.

**Comment by mavimo** [comment]
@mickadoo thanks, let me know if you see some issue in the current changes :)

**Comment by mavimo** [comment]
I'm going to tag 0.7 tomorrow after 8 PM (CET), let me know if someone find some issue that can be a release blocker :)
